version: 2
jobs:
  build:
      docker:
        -image: ckhrysze/elixir_for_amazonlinux2

      environment:
        MIX_ENV: prod
      working_directory: ~/repo
      steps:
        -checkout

        - run: mix local.hex --force
        - run: mix local.rebar
        - run: mix deps.get
        - run: mix working_directory
        - run: mix compile
        - run: mix npm install --prefix ./assets
        - run: mix phx.digest
        - run: mix mix release
        - run: cp _build/prod/nook_book-0.1.1.tar.gz nookbook.tgz

        - store_artifacts:
            path: nookbook.tgz
